# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6

# Set the build environment
env:
    global:
        - secure: JUNQHC6mafptpSpQqsQJNqhqg4hLfgrBEZFXRmPePXKSqcaoC4NnH7Fx1vGDQANHIgAspNDAhmbs7HY4bP43zJ24c+XuObpDn3TZmIHM0/yKZ/04vDdZIR09dk1qXt4zlTakT2jfuSm1YbCU5UI5NDKJryksY9eiK1VC/X9Ji+Ha2CJyj+I00jTYNfuqmu9BIFyvl26sMocfj3GEv9YIH77u+YXiCW4UDGKkb54LwznfUvqNdAa11visEQr9uK1uB9iwIo8lcfM6qEOMAmk84PvP2uOcCtUG92ryV+w+pege90xtlX4wy94N5xbx7kiEkfLMZpVolVv2HAkL4cmnAjEpv8orJYt8sc88Y2dilfrOnQqYEtI0kJvNsrwdYudPmmMLSxcHw6nWfBJ23k159dn3qeHuJQ1mCB/2ahEkZJsgqVt+9lwbFT2UU8tOqYOoaG8oC2dkYa0ZuNgcqbXZmUKfENizmf7kI8SzhBryoYA61G2YZ0HmwN4XROIcXpiNxIDFcKyxC/xzMmTm69xLSrmUmP1uaJdgY405pe8CyJVniaExx54LM8j0t/l48xI5EjkX9IpEVjHoa2OI8S2ph/LXtYNOgH0vV/4F6dUWZcyPZs2CQCA5eS3Gi0t67POdhgx8f374/G0RxlmLa4PcQh3+9nEDMj9EKpH7GO4/By0=
    - SMVERSION=1.7 # Legacy
    - SMVERSION=1.8 # Stable
    - SMVERSION=1.9 # Unstable
	

# And compile!
install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - cp hl_challenge.sp addons/sourcemod/scripting/
    - cp hl_challenge.inc addons/sourcemod/scripting/include
    - cd addons/sourcemod/scripting/include
    - wget "https://raw.githubusercontent.com/Impact123/AutoExecConfig/development/autoexecconfig.inc"
    - wget "https://raw.githubusercontent.com/dvarnai/store-plugin/master/addons/sourcemod/scripting/include/store.inc"
    - wget "https://raw.githubusercontent.com/splewis/csgo-multi-1v1/master/scripting/include/multi1v1.inc"
    - cd ..


    - chmod +x spcomp
    - mkdir compiled compiled/freaks
script: ./compile.sh hl_challenge.sp 

before_deploy:
    - cp -R compiled/* $TRAVIS_BUILD_DIR/addons/sourcemod/plugins/
    - cd $TRAVIS_BUILD_DIR
    - zip -r hl_challenge.zip addons/


deploy:
  provider: releases
  api_key:
      secure: MY_SECRET_ENV
  file: hl_challenge.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $SOURCEMOD = 1.7