# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6

# Set the build environment
env:
    - SMVERSION=1.7 # Legacy
    - SMVERSION=1.8 # Stable
    - SMVERSION=1.9 # Unstable

# And compile!
install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - cp hl_challenge.sp addons/sourcemod/scripting/
    - cp hl_challenge.inc addons/sourcemod/scripting/include
    - cd addons/sourcemod/scripting/include
    - wget "https://raw.githubusercontent.com/Impact123/AutoExecConfig/development/autoexecconfig.inc"
    - wget "https://raw.githubusercontent.com/dvarnai/store-plugin/master/addons/sourcemod/scripting/include/store.inc"
    - wget "https://raw.githubusercontent.com/splewis/csgo-multi-1v1/master/scripting/include/multi1v1.inc"
    - cd ..


    - chmod +x spcomp
    - mkdir compiled compiled/freaks
script: ./compile.sh hl_challenge.sp 

before_deploy:
    - cp -R compiled/* $TRAVIS_BUILD_DIR/addons/sourcemod/plugins/
    - cd $TRAVIS_BUILD_DIR
    - zip -r hl_challenge.zip addons/


deploy:
  provider: releases
  api_key:
      secure: "U82o2eDryuaENDuQ6a9wYbSqQHgqmU4yEJlGXdkBxML/ENQ8OUNTXHy47em83PZB/83A3deUjqxjZIv75nj6EfND0h0k3c/j81r8PwUs7Cghvw5+ljtefSHz7pWJ5Zc6hGEWcxj6xCs0zXjP595XJDj8AWbOw+Hf2CDqOlk/4FJ6eR6nKB3HZzdNQDh5uFl5aJ4gVpgiU+tHYcFMuHqlKM/qopcy1nwUtj3SaT6LQ6ZEdjM4fYl4bVVZhUMJ1Gqb2vQXFLdGNYolQ2c8CruBcnOBkr+4/9DOcXC69LVq3F6uofnVLYiUuUGo1YNoUKdvnFyrSnA3V/M5wGKI5DwFf4Q/R8EB93cTnusmjQskRALnVsIwZmRx8EBTa6jeVu0Uc8z0MOYr2BT48+AfTO5niYei6xxaJPAcTt3eA2iDomN/iZi3JPDPmfurn1usKQllWQ2WZ3z+elyIQFJWbNSFtq/0+f+0BIycX+moJ6hSSWNynF1tEgR7IAjr4gRw3Qfx8BBYzZz3uNFaLpwEcHwJs3E34wVjLrKcYqGYk2fIsO6e7zkT0z7myTBiS4TBaKCPnMLgSnOMWCmBnAScHkJ9AZHh79oZIGdmjVuaPTeCrSvS30+0FN7A4xgU+vDuYNRpVMOssX69Fi60YI6TL4qjycdAdMh+q3hG2FC6o3d5FhE="
  file: $TRAVIS_BUILD_DIR/build/package/hl_challenge.zip
  skip_cleanup: true
  on:
    repo: Headline22/Challenge
    tags: true
    all_branches: true